name: publish

on:
  push:
    branches:
      - main

env:
    # Use docker.io for Docker Hub if empty 
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.actor }}/${{ github.event.repository.name }}:latest 

jobs:
    publish:
        name: Publish Docker Image
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v3
        - name: Login
          run: |
            echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        - name: Build and Publish
          run: |
            docker build . --platform linux/amd64 --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 

    deploy:
        needs: publish
        name: Deploy Image to Server
        runs-on: ubuntu-latest

        steps:
        - name: install ssh keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        - name: install known_hosts
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: connect and pull
          run: ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker compose pull && docker compose up -d && exit"
        - name: cleanup
          run: rm -rf          

